### ISSUE TITLE
Formát otázky

### ISSUE THREAD

**Issue by badgercz** [fit-szz/szz-bootcamp#7]
Navrhuji změnit formát otázek tak, aby byly řazeny správně podle čísel, tedy by mělo stačit změnit např. "bi-spol-4" na "bi-spol-04", aby správně předcházela třeba "bi-spol-10"

**Comment by TomStary** [comment]
Klidně, jenom se po přejmenování všech položek říct @syyyr, aby přemazal data na build serveru.

**Comment by DanHampl** [comment]
nebo jen pouzit jinej radici algoritmus :)

**Comment by syyyr** [comment]
Nahoďte commit, já to pak promažu, nebo to můžu po successful buildu promazat vždycky, jak chcete

**Comment by lossantlos** [comment]
Souhlasím možná třeba formát: SPOL-{cislo:02}-{předmět} aby se v tom dalo orientovat i bez seznamu? Předpona bi mi taky přijde jako zbytečný psaní dalších písmen navíc.

**Comment by syyyr** [comment]
Přejmenoval jsem zatím ty jednočíslicový předměty a promazal build adresář. Jinou změnu formátu vidím jako zbytečnou (jednak pro to, že nic neřeší, a druhak proto, že by to mohlo zkomplikovat makefile).

**Comment by TomStary** [comment]
Dávám closed, řazení je opraveno a změna formátu se konat nebude.
